[package]
name = "adsbee-mode-s"
version = "0.1.0"
edition = "2024"

[dependencies.adsbee-types]
workspace = true

[dependencies]
bytes = "1.10.1"
crc = "3.3.0"
thiserror = "2.0.12"
tracing = "0.1.41"

[dev-dependencies]
approx = "0.5.1"
