[package]
name = "adsbee-sbs"
version = "0.1.0"
edition = "2024"

[dependencies.adsbee-types]
workspace = true

[dependencies]
chrono = { version = "0.4.41", default-features = false }
futures-util = "0.3.31"
pin-project-lite = "0.2.16"
thiserror = "2.0.12"
tokio = "1.46.0"
tracing = "0.1.41"
